routes/cliente.py
from flask import Blueprint, render_template, request, flash, session, redirect, url_for
from controllers.database import Conexion as dbase
from modules.cliente import Cliente
from pymongo import MongoClient
db = dbase()

cliente = Blueprint('cliente', __name__)


# Ingreso con un Id unico
@cliente.route('/admin/in_cliente',methods=['GET','POST'])
def adcli():
    if 'username' not in session:
        flash("Inicia sesion con tu usuario y contraseña")
        return redirect(url_for('cliente.index'))  # Redirige al usuario al inicio si no está en la sesión
    

    if request.method == 'POST':
        cliente = db["cliente"]
        nombre = request.form['nombre']
        apellido = request.form['apellido']
        cedula = request.form['cedula']
        direccion = request.form['direccion']
        telefono = request.form['telefono']
        correo = request.form['correo']

        exist_cedula = cliente.find_one({"cedula": cedula})
        exist_telefono = cliente.find_one({"telefono": telefono})
        exist_correo = cliente.find_one({"correo": correo})

        if exist_cedula:
            flash("La cedula ya existe" , "danger")
            return redirect(url_for('cliente.adcli'))
        elif exist_telefono:
            flash("El celular ya existe" ,"danger")
            return redirect(url_for('cliente.adcli'))
        elif exist_correo:
            flash("El correo ya existe" , "danger")
            return redirect(url_for('cliente.adcli'))
        else:
            client = Cliente( nombre, apellido, cedula, direccion, telefono, correo)
            cliente.insert_one(client.ClienteDBCollection())
            flash("Enviado a la base de datos" , "success")
            return redirect(url_for('cliente.adcli'))
    else:
        return render_template('admin/in_cliente.html',message=request.args.get('message'))
        
@cliente.route('/edit_cli/<string:edacli>', methods=['GET', 'POST'])#
def edit_cli(edacli):
    cliente = db['cliente']
    nombre = request.form["nombre"]
    apellido = request.form["apellido"]
    cedula = request.form['cedula']
    direccion = request.form["direccion"]
    telefono = request.form["telefono"]
    correo = request.form['correo']
    
    if nombre and apellido  and cedula and direccion and telefono and correo:
        cliente.update_one({'cedula' : edacli}, {'$set' : {'nombre' : nombre, 'apellido' : apellido, 'cedula' : cedula ,"direccion" :direccion , "telefono" : telefono , "correo" : correo}})
        flash("Cliente  "+ nombre + " con  cedula " + cedula + " editado correctamente " , "success")
        return redirect(url_for('cliente.v_cli'))
    else:
        return render_template('admin/cliente.html')

# * Eliminar cliente
@cliente.route('/delete_cli/<string:eliacli>')
def delete_cli(eliacli):
    cliente = db["cliente"]
    documento =  cliente.find_one({"cedula":eliacli})
    nombre = documento["nombre"]
    apellido = documento["apellido"]
    cedula = documento["cedula"]
    cliente.delete_one({"cedula":eliacli})
    flash("Cliente  "+ nombre +" "+ apellido +" con cedula " + cedula  + " eliminado correctamente" , "success") 
    return redirect(url_for('cliente.v_cli'))

# Visualizar cliente
@cliente.route("/admin/cliente")
def v_cli():
    if 'username' not in session:
        flash("Inicia sesion con tu usuario y contraseña")
        return redirect(url_for('cliente.index'))
    cliente = db['cliente'].find()
    return render_template("admin/cliente.html", cliente=cliente)

routes/marca.py
from flask import Blueprint, render_template, request, flash, session, redirect, url_for, current_app
from controllers.database import Conexion as dbase
from werkzeug.utils import secure_filename
import os
from modules.marca import Marca
from pymongo import MongoClient
db = dbase()

marca = Blueprint('marca', __name__)


# Este codigo es para lo que es el ID
def get_next_sequence(name): 
    seq = db.seqs.find_one({'_id': name})
    if seq is None:
        # Inicializa 'productoId' en 220 si no existe
        db.seqs.insert_one({'_id': 'marcaId', 'seq': 0})
        seq = db.seqs.find_one({'_id': name})

    result = db.seqs.find_one_and_update(
        {'_id': name},
        {'$inc': {'seq': 1}},
        return_document=True
    )
    return result.get('seq')

# Ingresar con un id marca
@marca.route('/admin/in_marca',methods=['GET','POST'])
def in_marca():
    if 'username' not in session:
        flash("Inicia sesion con tu usuario y contraseña")
        return redirect(url_for('marca.index'))  # Redirige al usuario al inicio si no está en la sesión
    
    if request.method == 'POST':
        id_marca = str(get_next_sequence('marcaId')).zfill(3)
        marca = db["marca"]
        nombre = request.form['nombre']
        proveedor = request.form['proveedor']
        comentario = request.form['comentario']

        exist_nombre = marca.find_one({"nombre": nombre})

        if exist_nombre:
            flash("El nombre de la marca ya existe", "danger")
            return redirect(url_for('marca.in_marca'))
        
        else:
            mar = Marca(id_marca, nombre, proveedor, comentario)
            marca.insert_one(mar.MarcaDBCollection())
            flash("Marca enviada a la base de datos", "success")
            return redirect(url_for('marca.in_marca'))
    else:
        return render_template('admin/in_marca.html', message=request.args.get('message'))
    
@marca.route('/edit_marca/<string:edamarca>', methods=['GET', 'POST'])#
def edit_marca(edamarca):
    marca = db['marca']
    nombre = request.form["nombre"]
    proveedor = request.form["proveedor"]
    comentario = request.form["comentario"]
    
    if nombre and proveedor and comentario:
        marca.update_one({'id_marca' : edamarca}, {'$set' : {'nombre' : nombre, 'proveedor' : proveedor, 'comentario' : comentario}})
        flash("Marca  "+ nombre + " editada correctamente " , "success")
        return redirect(url_for('marca.v_marca'))
    else:
        flash("Error al editar la marca", "danger")
        return redirect(url_for('marca.v_marca'))

# Eliminar marca
@marca.route('/del_marca/<string:delmarca>', methods=['GET', 'POST'])
def del_marca(delmarca):
    marca = db['marca']
    marca.delete_one({'id_marca': delmarca})
    flash("Marca eliminada correctamente", "success")
    return redirect(url_for('marca.v_marca'))

# Mostrar marcas
@marca.route('/admin/marca', methods=['GET'])
def v_marca():
    if 'username' not in session:
        flash("Inicia sesion con tu usuario y contraseña")
        return redirect(url_for('marca.index'))
    marcas = db['marca'].find()
    return render_template('admin/marca.html', marcas=marcas)


# Mostrar marcas
@marca.route('/user/marca', methods=['GET'])
def u_marca():
    if 'username' not in session:
        flash("Inicia sesion con tu usuario y contraseña")
        return redirect(url_for('marca.index'))
    marcas = db['marca'].find()
    return render_template('user/marca.html', marcas=marcas)

routes/venta.py
from flask import Blueprint, make_response,send_file, render_template, request, flash, session, redirect, url_for
from controllers.database import Conexion as dbase
from modules.venta import Venta
from pymongo import MongoClient
from flask import jsonify
from bson import ObjectId
from reportlab.pdfgen import canvas # *pip install reportlab este es para imprimir reportes
from reportlab.lib.pagesizes import letter #* pip install reportlab 
from reportlab.lib.units import inch
from reportlab.pdfbase import pdfmetrics
from reportlab.pdfbase.ttfonts import TTFont
from reportlab.platypus import SimpleDocTemplate, Table, Paragraph, TableStyle, Spacer ,Image
from reportlab.lib import colors
from reportlab.lib.styles import getSampleStyleSheet ,ParagraphStyle
import io
from flask import Flask
db = dbase()
from mail_config import mail
from flask_mail import Message
# Importar mail después de definir el Blueprint



venta = Blueprint('venta', __name__)

mail = None

# Función para inicializar mail
def init_mail(mail_instance):
    global mail
    mail = mail_instance

# Este codigo es para lo que es el ID
def get_next_sequence(name): 
    seq = db.seqs.find_one({'_id': name})
    if seq is None:
        # Inicializa 'productoId' en 220 si no existe
        db.seqs.insert_one({'_id': 'ventaId', 'seq': 0})
        seq = db.seqs.find_one({'_id': name})

    result = db.seqs.find_one_and_update(
        {'_id': name},
        {'$inc': {'seq': 1}},
        return_document=True
    )
    return result.get('seq')

@venta.route("/admin/in_venta", methods=['GET', 'POST'])
def adventa():
    if 'username' not in session:
        flash("Inicia sesion con tu usuario y contraseña")
        return redirect(url_for('cliente.index'))
    
    cliente = db["cliente"].find()
    producto = db["producto"].find()

    if request.method == 'POST':
        id_venta = str(get_next_sequence('ventaId')).zfill(1)
        venta = db["venta"]
        n_cliente = request.form["n_cliente"]
        n_apellido = request.form["n_apellido"]
        direccion = request.form["direccion"]
        cedula = request.form["cedula"]
        fecha = request.form["fecha"]
        hora = request.form["hora"]
        usi = request.form["usuario"]
        # Recoger los productos
        id_productos = request.form.getlist("id_producto")
        n_productos = request.form.getlist("n_productos")
        talla = request.form.getlist("talla")
        colores = request.form.getlist("color")
        cantidades = request.form.getlist("cantidad")
        precios = request.form.getlist("precio")
        resultados = request.form.getlist("resultado")
        totales = request.form.getlist("total")
         
       

        productos = []
        for i in range(len(n_productos)):
            producto = {
                "id_producto": id_productos[i] if i < len(id_productos) else '',
                "n_producto": n_productos[i] if i < len(n_productos) else '',
                "talla": talla[i] if i < len(talla) else '',
                "color": colores[i] if i < len(colores) else '',
                "cantidad": cantidades[i] if i < len(cantidades) else '',
                "precio": precios[i] if i < len(precios) else '',
                "resultado": resultados[i] if i < len(resultados) else '',
                "total": totales[i] if i < len(totales) else ''
            }
            productos.append(producto)

        # Crear el documento de venta
        venta_documento = {
            "id_venta": id_venta,
            "n_cliente": n_cliente,
            "n_apellido": n_apellido,
            "direccion": direccion,
            "cedula": cedula,
            "fecha": fecha,
            "hora": hora,
            "productos": productos,
            "usuario":usi
        }
        
        # Insertar el documento en la colección de ventas
        venta.insert_one(venta_documento)
        print("Documento de Venta:", venta_documento)

        # Actualizar las cantidades de los productos
        for i in range(len(id_productos)):
            id_producto = id_productos[i]
            cantidad_vendida = cantidades[i]
            
            if cantidad_vendida:
                cantidad_vendida = int(cantidad_vendida)
            
                # Obtener el producto de la base de datos
                producto_db = db["producto"].find_one({"id_producto": id_producto})
                if producto_db:
                    nueva_cantidad = int(producto_db["cantidad"]) - cantidad_vendida
                    # Actualizar la cantidad del producto en la base de datos
                    db["producto"].update_one({"id_producto": id_producto}, {"$set": {"cantidad": str(nueva_cantidad)}})
                    print(f"Producto {id_producto} actualizado. Nueva cantidad: {nueva_cantidad}")
            else:
                print(f"Cantidad no válida para el producto {id_producto}")

        flash("Venta registrada con éxito y cantidades actualizadas","success")
        return redirect(url_for('venta.adventa'))

    else:
        return render_template("admin/in_venta.html", cliente=cliente, producto=producto)




# Visualizar venta
@venta.route("/admin/venta")
def v_cli():
    if 'username' not in session:
        flash("Inicia sesion con tu usuario y contraseña")
        return redirect(url_for('venta.index'))
    venta = db['venta'].find()
    return render_template("admin/venta.html", venta=venta)



# Visualizar detalles del cliente por ID y que se pueda revisar 
@venta.route("/admin/venta/<id>")
def v_cliente(id):
    if 'username' not in session:
        flash("Inicia sesión con tu usuario y contraseña")
        return redirect(url_for('venta.index'))
    cliente = db['venta'].find_one({"_id": ObjectId(id)})
    return render_template("admin/v_cliente.html", cliente=cliente)

# Visualizar venta usuarios
@venta.route("/user/venta")
def u_cli():
    if 'username' not in session:
        flash("Inicia sesion con tu usuario y contraseña")
        return redirect(url_for('venta.index'))
    venta = db['venta'].find({"usuario": session['username']})
    return render_template("user/venta.html", venta=venta)

    

# Nueva ruta para generar el PDF
@venta.route("/admin/venta/<id>/pdf")
def generar_pdf(id):
    if 'username' not in session:
        flash("Inicia sesión con tu usuario y contraseña")
        return redirect(url_for('venta.index'))
    
    cliente = db['venta'].find_one({"_id": ObjectId(id)})
    
    if not cliente:
        flash("Cliente no encontrado")
        return redirect(url_for('venta.index'))
    
    # Crear el PDF en memoria
    buffer = io.BytesIO()
    c = canvas.Canvas(buffer, pagesize=letter)
    width, height = letter
    
    # Título
    c.setFont("Helvetica-Bold", 20)
    c.drawCentredString(width / 2.0, height - 50, "MODAMENSPLUS")
    
    # Detalles del cliente
    c.setFont("Helvetica", 12)
    c.drawString(50, height - 100, f"FACTURA: {cliente['id_venta']}")
    c.drawString(50, height - 120, f"Nombre: {cliente['n_cliente']}")
    c.drawString(50, height - 140, f"Apellido: {cliente['n_apellido']}")
    c.drawString(50, height - 160, f"Direccion: {cliente['direccion']}")
    c.drawString(50, height - 180, f"Cedula: {cliente['cedula']}")
    c.drawString(50, height - 200, f"Fecha: {cliente['fecha']}")
    
    # Tabla de productos
    c.drawString(50, height - 240, "Nombre de los productos")
    c.drawString(200, height - 240, "Talla")
    c.drawString(250, height - 240, "Color")
    c.drawString(350, height - 240, "Cantidad")
    c.drawString(450, height - 240, "Precio $")
    c.drawString(550, height - 240, "Total")
    
    y = height - 260
    for producto in cliente['productos']:
        c.drawString(50, y, producto['n_producto'])
        c.drawString(200, y, producto['talla'])
        c.drawString(250, y, producto['color'])
        c.drawString(350, y, str(producto['cantidad']))
        c.drawString(450, y, str(producto['precio']))
        c.drawString(550, y, str(producto['resultado']))
        y -= 20
    
    # Total
    c.setFont("Helvetica-Bold", 14)
    c.drawString(50, y - 40, f"Total: {cliente['productos'][0]['total']}")
    
    c.showPage()
    c.save()
    
    buffer.seek(0)
    
    return send_file(buffer, as_attachment=True, download_name=f'factura_{cliente["id_venta"]}.pdf', mimetype='application/pdf')



# Función para obtener el correo del cliente
def obtener_correo_cliente(cedula):
    cliente = db['cliente'].find_one({"cedula": cedula})
    if cliente:
        return cliente.get('correo')
    return None

# Función para generar el PDF
def generar_pdf_cliente(cliente):
    buffer = io.BytesIO()
    c = canvas.Canvas(buffer, pagesize=letter)
    width, height = letter
    
    # Título
    c.setFont("Helvetica-Bold", 20)
    c.drawCentredString(width / 2.0, height - 50, "MODAMENSPLUS")
    
    # Detalles del cliente
    c.setFont("Helvetica", 12)
    c.drawString(50, height - 100, f"FACTURA: {cliente['id_venta']}")
    c.drawString(50, height - 120, f"Nombre: {cliente['n_cliente']}")
    c.drawString(50, height - 140, f"Apellido: {cliente['n_apellido']}")
    c.drawString(50, height - 160, f"Direccion: {cliente['direccion']}")
    c.drawString(50, height - 180, f"Cedula: {cliente['cedula']}")
    c.drawString(50, height - 200, f"Fecha: {cliente['fecha']}")
    
    # Tabla de productos
    c.drawString(50, height - 240, "Nombre de los productos")
    c.drawString(200, height - 240, "Talla")
    c.drawString(250, height - 240, "Color")
    c.drawString(350, height - 240, "Cantidad")
    c.drawString(450, height - 240, "Precio $")
    c.drawString(550, height - 240, "Total")
    
    y = height - 260
    for producto in cliente['productos']:
        c.drawString(50, y, producto['n_producto'])
        c.drawString(200, y, producto['talla'])
        c.drawString(250, y, producto['color'])
        c.drawString(350, y, str(producto['cantidad']))
        c.drawString(450, y, str(producto['precio']))

templates/user/cliente.html
{% extends "user/layout.html" %}
{% block content %}
<div id="page-wrapper">
    <div id="page-inner">
        <div class="row">
            <div class="col-md-12">
                <h1 class="page-head-line animate__animated animate__backInLeft">Visualizar Cliente</h1>
                </h1>
            </div>
        </div>

        {% with messages = get_flashed_messages() %}
        {% if messages %}
        <div class="alert alert-danger" style="background-color: #00CA79;">
            {{ messages[0] }}
        </div>
        {% endif %}
        {% endwith %}


        <div class="animate__animated animate__backInLeft">
            <!-- /. ROW  -->
            <table class="table table-bordered table-hover" id="myTable">
                <thead>
                    <tr>
                        <th>Nombre</th>
                        <th>Apellido</th>
                        <th>Cedula</th>
                        <th>Direccion</th>
                        <th>Telefono</th>
                        <th>Correo</th>

                    </tr>
                </thead>
                <tbody>
                    {% for cliente in cliente %}
                    <tr>
                        <td>{{ cliente.nombre }}</td>
                        <td>{{ cliente.apellido }}</td>
                        <td>{{ cliente.cedula }}</td>
                        <td>{{ cliente.direccion }}</td>
                        <td>{{ cliente.telefono }}</td>
                        <td>{{ cliente.correo }}</td>

                    </tr>
                    </form>
                    {% endfor %}
                </tbody>
            </table>
        </div>
    </div>
</div>

<script>
    $(document).ready(function () {
        $('#myTable').DataTable({
            "language": {
                "url": "/static/assets/js/Spanish.json"
            }
        });
        var table = $('#myTable').DataTable();
    });
</script>


{% endblock %}

templates/user/in_cliente.html
{% extends "user/layout.html" %}
{% block content %}
<div id="page-wrapper">
    <div id="page-inner">
        <div class="row">
            <div class="col-md-12">
                <h1 class="page-head-line animate__animated animate__backInLeft">
                    Ingresar Clientes
                </h1>
                </h1>
            </div>
        </div>
        <!-- /. ROW  -->
        {% with messages = get_flashed_messages(with_categories=true) %}
        {% if messages %}
        {% for category, message in messages %}
        <div class="alert alert-{{ category }}">
            {{ message }}
        </div>
        {% endfor %}
        {% endif %}
        {% endwith %}
        <div class="col-md-12 col-sm-12 col-xs-12 rojo">
            <div class="panel panel-info">
                <div class="panel-heading"  >
                    Llenar el formulario
                </div>
                <div class="panel-body animate__animated animate__backInLeft">
                    <form action="/user/in_cliente" method="post">
                        <div class="form-group">
                            <label >Cedula</label>
                            <input class="form-control" name="cedula" type="number" oninput="limitarEntrada()">
                        </div>
                        <div class="form-group">
                            <label >Nombre del cliente</label>
                            <input class="form-control" name="nombre" type="text">
                        </div>
                        <div class="form-group">
                            <label >Apellido</label>
                            <input class="form-control" name="apellido" type="text">
                        </div>
                        <div class="form-group">
                            <label>Direccion</label>
                            <input class="form-control" name="direccion" type="text">
                        </div>
                        <div class="form-group">
                            <label>Celular</label>
                            <input class="form-control" name="telefono" type="text">
                        </div>
                        <div class="form-group">
                            <label>Correo</label>
                            <input class="form-control" name="correo" type="email">
                        </div>
                        <button type="submit" style="background-color: #428BCA; color: white; padding: 10px 20px; border: none; border-radius: 5px; cursor: pointer;">📦 Guardar</button>
                    </form>
                </div>
            </div>
        </div>
        <!--/.ROW-->
    </div>
    <!-- /. PAGE INNER  -->
</div>
<script src="/static/assets/js/validaciones/user.js"></script>
{% endblock %}

templates/user/marca.html
{% extends "user/layout.html" %}
{% block content %}
<div id="page-wrapper">
    <div id="page-inner">
        <div class="row">
            <div class="col-md-12">
                <h1 class="page-head-line animate__animated animate__backInLeft">Visualizar Marca</h1>
                </h1>
            </div>
        </div>
        {% with messages = get_flashed_messages() %}
        {% if messages %}
        <div class="alert alert-danger" style="background-color: #00CA79;">
            {{ messages[0] }}
        </div>
        {% endif %}
        {% endwith %}
        <div class="animate__animated animate__backInLeft">
            <!-- /. ROW  -->
            <table class="table table-bordered table-hover" id="myTable">
                <thead>
                    <tr>
                        <th >Codigo</th>
                        <th>Nombre</th>
                        <th>Proveedor</th>
                        <th>Comentario</th>
                        
                    </tr>
                </thead>
                <tbody>
                    {% for marcas in marcas %}
                    <tr>
                        <td >
                            {{marcas.id_marca}}
                        </td>
                        <td>
                            {{marcas.nombre}}
                        </td>
                        <td>
                            {{marcas.proveedor}}
                        </td>
                        <td>
                            {{marcas.comentario}}
                        </td>
                        
                    </tr>
                    </form>
                    {% endfor %}
                </tbody>
            </table>
        </div>
    </div>
</div>

<!--/.ROW-->
</div>
<!-- /. PAGE INNER  -->
</div>

{% endblock %}

templates/user/producto.html
{% extends "user/layout.html" %}
{% block content %}
<div id="page-wrapper">
    <div id="page-inner">
        <div class="row">
            <div class="col-md-12">
                <h1 class="page-head-line animate__animated animate__backInLeft">Visualizar Productos</h1>
                </h1>
            </div>
        </div>
        {% with messages = get_flashed_messages() %}
        {% if messages %}
        <div class="alert alert-danger" style="background-color: #00CA79;">
            {{ messages[0] }}
        </div>
        {% endif %}
        {% endwith %}
        <div class="animate__animated animate__backInLeft">
            <!-- /. ROW  -->
            <table class="table table-bordered table-hover" id="myTable">
                <thead>
                    <tr>
                        <th >Codigo</th>
                        <th>Nombre</th>
                        <th>Precio</th>
                        <th>Color</th>
                        <th>Imagen</th>
                        <th>Marca</th>
                        <th>Cantidad</th>
                        
                    </tr>
                </thead>
                <tbody>
                    {% for producto in producto %}
                    <tr>
                        <td >
                            {{producto.id_producto}}
                        </td>
                        <td>
                            {{producto.nombre}}
                        </td>
                        <td>
                            {{producto.precio}}
                        </td>
                        <td>
                            {{producto.color}}
                        </td>
                        <td>
                            <!-- Asegúrate de incluir la subcarpeta 'img' si es necesario -->
                            <img src="{{ url_for('static', filename='assets/img/' + producto.imagen) }}" alt="Imagen de herramienta" width="50">
                            
                        </td>    
                        <td>
                            {{producto.marca}}
                        </td>                   
                        <td>
                            {{producto.cantidad}}
                        </td>

                    </tr>
                    
                    {% endfor %}
                </tbody>
            </table>
        </div>
    </div>
</div>





<script>
    $(document).ready(function () {
        $('#myTable').DataTable({
            "language": {
                "url": "/static/assets/js/Spanish.json"
            }
        });
        var table = $('#myTable').DataTable();
    });
</script>

{% endblock %}

templates/user/venta.html
{% extends "user/layout.html" %}
{% block content %}
<div id="page-wrapper">
    <div id="page-inner">
        <div class="row">
            <div class="col-md-12">
                <h1 class="page-head-line animate__animated animate__backInLeft">Visualizar Venta</h1>
                </h1>
            </div>
        </div>
        {% with messages = get_flashed_messages() %}
        {% if messages %}
        <div class="alert alert-danger" style="background-color: #00CA79;">
            {{ messages[0] }}
        </div>
        {% endif %}
        {% endwith %}
        <div class="animate__animated animate__backInLeft">
            <!-- /. ROW  -->
            <table class="table table-bordered table-hover" id="myTable">
                <thead>
                    <tr>
                        <th>Cedula</th>
                        <th>Nombre</th>
                        <th>Fecha</th>
                        <th>Hora</th>
                        <th>Total</th>
                        <th>Acciones</th>
                    </tr>
                </thead>
                <tbody>
                    {% for venta in venta %}
                    <tr>
                        <td>
                            {{ venta.cedula }}
                        </td>
                        <td>
                            {{ venta.n_cliente }}
                        </td>
                        <td>
                            {{ venta.fecha }}
                        </td>
                        <td>
                            {{ venta.hora }}
                        </td>
                        <td>
                            {{ venta.productos[0].total }}
                        </td>
                        <td>
                            <a href="{{ url_for('venta.v_cliente', id=venta._id) }}">
                            <svg xmlns="http://www.w3.org/2000/svg" width="16" height="16" fill="currentColor"
                                class="bi bi-file-earmark-bar-graph-fill" viewBox="0 0 16 16">
                                <path
                                    d="M9.293 0H4a2 2 0 0 0-2 2v12a2 2 0 0 0 2 2h8a2 2 0 0 0 2-2V4.707A1 1 0 0 0 13.707 4L10 .293A1 1 0 0 0 9.293 0M9.5 3.5v-2l3 3h-2a1 1 0 0 1-1-1m.5 10v-6a.5.5 0 0 1 .5-.5h1a.5.5 0 0 1 .5.5v6a.5.5 0 0 1-.5.5h-1a.5.5 0 0 1-.5-.5m-2.5.5a.5.5 0 0 1-.5-.5v-4a.5.5 0 0 1 .5-.5h1a.5.5 0 0 1 .5.5v4a.5.5 0 0 1-.5.5zm-3 0a.5.5 0 0 1-.5-.5v-2a.5.5 0 0 1 .5-.5h1a.5.5 0 0 1 .5.5v2a.5.5 0 0 1-.5.5z" />
                            </svg>
                        </a>
                        </td>
                    </tr>
                    {% endfor %}
                </tbody>
            </table>
        </div>
    </div>
</div>
<script>
    $('#myTable').DataTable({
            "language": {
                "url": "/static/assets/js/Spanish.json"
            }
        });
        var table = $('#myTable').DataTable();
</script>
{% endblock %}